# This file was generated by GoReleaser. DO NOT EDIT.
cask "ntm" do
  name "ntm"
  desc "Named Tmux Manager - Orchestrate AI coding agents in tmux sessions"
  homepage "https://github.com/Dicklesworthstone/ntm"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ntm"
  bash_completion "ntm completion bash"
  zsh_completion "ntm completion zsh"
  fish_completion "ntm completion fish"
  depends_on formula: [
      "tmux",
    ]

  on_macos do
    url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_darwin_all.tar.gz"
    sha256 "c15fbedbb7b981bec91f5d9b6ae7a4ce88c81d7663426e7f4d9b4ee4e39af69c"
  end

  on_linux do
    on_intel do
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_amd64.tar.gz"
      sha256 "c895c91a03a72928baea8d9a31a85492e8cdda6a4ae40da650d042815651126b"
    end
    on_arm do
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_arm64.tar.gz"
      sha256 "a53d2306977fc7d8715edfdb1827a68a59b9eaf1ce7e7819dccc2ca80f342b79"
    end
  end

  caveats do
    "To enable shell integration, add to your shell rc file:"
    ""
    "  eval "$(ntm init zsh)"   # for zsh"
    "  eval "$(ntm init bash)"  # for bash"
    "  eval "$(ntm init fish)"  # for fish"
    ""
    "Run 'ntm tutorial' to get started!"
  end

  # No zap stanza required
end
