# This file was generated by GoReleaser. DO NOT EDIT.
cask "ntm" do
  version "1.13.0"

  on_macos do
    url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_darwin_all.tar.gz"
    sha256 "749f68038975eb4c31fc3899f22490bdc351dbd213eb356e116c16e9e946dbe3"
  end

  on_linux do
    on_intel do
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_amd64.tar.gz"
      sha256 "2240cec546c4702f7f895849906b2e25d54f0abe79b4b839718540ff13ec97db"
    end
    on_arm do
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_arm64.tar.gz"
      sha256 "3457d2c9dd65c463369c65739e5180f659e7e982d2d2011ebeafb57edd4efdbc"
    end
  end

  name "ntm"
  desc "Named Tmux Manager - Orchestrate AI coding agents in tmux sessions"
  homepage "https://github.com/Dicklesworthstone/ntm"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "ntm"

  # No zap stanza required

  caveats <<~EOS
    To complete installation, add the following to your shell config:

      # For zsh (add to ~/.zshrc):
      eval "$(ntm shell zsh)"

      # For bash (add to ~/.bashrc):
      eval "$(ntm shell bash)"

    Run 'ntm tutorial' to get started!
  EOS
end
