# This file was generated by GoReleaser. DO NOT EDIT.
cask "ntm" do
  version "1.14.0"

  on_macos do
    sha256 "b82f605a177fb2c750a1abbf0158bea09551446ed24482aba3a8c3456c13351a"
    url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "a4946fd28577bb4473187691325f60f92b2b32e35eaa1c864c2cd3ce4b363cd1"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd5daa623613d6ab1f2926c72bc25aa5f171aaf498b76c8cae9ab8d70ee165db"
      url "https://github.com/Dicklesworthstone/ntm/releases/download/v#{version}/ntm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ntm"
  desc "Named Tmux Manager - Orchestrate AI coding agents in tmux sessions"
  homepage "https://github.com/Dicklesworthstone/ntm"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "ntm"

  # No zap stanza required

  caveats <<~EOS
    To complete installation, add the following to your shell config:

      # For zsh (add to ~/.zshrc):
      eval "$(ntm shell zsh)"

      # For bash (add to ~/.bashrc):
      eval "$(ntm shell bash)"

    Run 'ntm tutorial' to get started!
  EOS
end
