# This file was generated by GoReleaser. DO NOT EDIT.
cask "slb" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "c8c2d745a95d702b65c6ae42fe8f8c56633ce2585857fe635af9a8a3e6ae9109"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "185bef18d345f406692430929860edbfc092a9e9406b868471eed2365e438bc6"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0b9c489fe025d77c8e0d6b992b2cd94d46e74a2a294e480c57274df5d634027b"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "88f3ec9cb5fa03431b13ed840423c7d0946ca32b4a3dcc0edd5a0f934419917d"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slb"
  desc "Simultaneous Launch Button - Two-person rule for dangerous commands"
  homepage "https://github.com/Dicklesworthstone/slb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slb"

  # No zap stanza required

  caveats <<~EOS
    SLB (Simultaneous Launch Button) implements two-person authorization.

    Quick start:
      slb init                  # Initialize in current project
      slb create "rm -rf /"     # Create a launch request
      slb list                  # List pending requests
  EOS
end
