# This file was generated by GoReleaser. DO NOT EDIT.
cask "slb" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "8c0614b235be236fc389254ec5cd2378a6e9cf61d7805e6cd7027286feaa5210"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "901a5ac955305047dc66660366eb214c96a2c195345e6ae29c24232e716ef602"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83462fc09ac800bc922d15e0d4890de9331f783182c1346b99d9f18d91bc8402"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "24118b92fd9537cec667fe325ff05f0374e479d538bcee8e6cfa72ad7d3bd0fb"
      url "https://github.com/Dicklesworthstone/slb/releases/download/v#{version}/slb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slb"
  desc "Simultaneous Launch Button - Two-person rule for dangerous commands"
  homepage "https://github.com/Dicklesworthstone/slb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slb"

  # No zap stanza required

  caveats <<~EOS
    SLB (Simultaneous Launch Button) implements two-person authorization.

    Quick start:
      slb init                  # Initialize in current project
      slb create "rm -rf /"     # Create a launch request
      slb list                  # List pending requests
  EOS
end
