# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bv < Formula
  desc "Graph-aware task management TUI for beads projects"
  homepage "https://github.com/Dicklesworthstone/beads_viewer"
  version "0.16.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Dicklesworthstone/beads_viewer/releases/download/v0.16.2/bv_0.16.2_darwin_amd64.tar.gz"
      sha256 "9fec91bd177be462e22671ad118dfb018ca55c38db783b1890b63153cb810573"

      def install
        bin.install "bv"
      end
    end
    on_arm do
      url "https://github.com/Dicklesworthstone/beads_viewer/releases/download/v0.16.2/bv_0.16.2_darwin_arm64.tar.gz"
      sha256 "8e74ff0aefc61f830865f0ec4b758be3854bbbc77353c39643fd8356fb26438c"

      def install
        bin.install "bv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Dicklesworthstone/beads_viewer/releases/download/v0.16.2/bv_0.16.2_linux_amd64.tar.gz"
        sha256 "aa05569c316c97c7c722af680444706e1f426637c04ff31b9a0659b4671a64b3"

        def install
          bin.install "bv"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Dicklesworthstone/beads_viewer/releases/download/v0.16.2/bv_0.16.2_linux_arm64.tar.gz"
        sha256 "26125bf22de7935bdd8b99444bd13cb5370f99115e7404090f468e42a05acf1c"

        def install
          bin.install "bv"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started with bv:
        1. Initialize beads in your project: br init
        2. Launch the TUI: bv

      For AI agent integration, use --robot-* flags:
        bv --robot-triage     # Get prioritized recommendations
        bv --robot-next       # Get single next action
    EOS
  end

  test do
    system "#{bin}/bv", "--version"
  end
end
