# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caam < Formula
  desc "CLI tool for managing AI coding agent accounts and configurations"
  homepage "https://github.com/Dicklesworthstone/coding_agent_account_manager"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.4/caam_0.1.4_darwin_amd64.tar.gz"
      sha256 "1ab769284cb8aef49c1603fecc517c5cb980534cb522825d84033a7aebea1b67"

      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.4/caam_0.1.4_darwin_arm64.tar.gz"
      sha256 "8cfd655e3fe1149f8afaf30ea14d829e4e57a78a2e8b20931cfca882dc418483"

      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.4/caam_0.1.4_linux_amd64.tar.gz"
      sha256 "f76177786968d410e126812127e88613faebdbf7029e1eac749c08d12809edce"
      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dicklesworthstone/coding_agent_account_manager/releases/download/v0.1.4/caam_0.1.4_linux_arm64.tar.gz"
      sha256 "38abf42b54da2e2ea5b25efb62cf7338812ae94d0e7bc026dec96053d3a0b275"
      def install
        bin.install "caam"
        generate_completions_from_executable(bin/"caam", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      To get started with caam:
        caam list              # List configured accounts
        caam switch <account>  # Switch to an account
        caam add               # Add a new account
    EOS
  end

  test do
    system "#{bin}/caam", "--version"
  end
end
